language: python
sudo: required
python:
    - "2.7"
env:
    CKANVERSION=2.7
install:
    - bash bin/travis-build.bash
    - pip install coveralls
services:
     -postgresql
script: sh bin/travis-run.sh
after_success:
    - coveralls
